# //! Useless File Because the codegen is not working in to this file 
query videoBlogContexts{
  videoBlogContexts {
    id
    title
    url
  }
},


query VideoBlogContextById($videoId: ID!) {
  videoBlogContext(id: $videoId) {
    id
    title
    url
  }
}
